# -*- coding: utf-8 -*-
"""hw1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QdmiAlZY9NoNbNlFI2aySosi21QD7far

**Saif Khawaja 87474921**

**STAT431 HW1**

*Question 1*

1. Observational study (scientists have no control over a mother's behavior).

2. Yes: positive association of body fat with controlling behavior.

3. Controlling behavior could serve as a premise for explanation but is not conclusive for confounding variables (eating more, for example, does not necessitate a higher rate of obesity - controlling mothers can also push children to exercise...)

4. Said gene can be controlled for in subsequent experiments such that we can find controlled associations but is only a small sample and will not reflect the entire population. The inferred data collected in the study does not reflect any genetic qualities and so does not explain the changes. 

5. There are many alternative and intermediate reasons why there is an association, such as if the type of food a controlling mother would cook had a higher percentage of fat.  

6. One can argue that the data supports the advice as a statment but it is inconclusive and requires more stringent intermediate analysis that studies confounding variables for a conclusion to be drawn.

*Question 2* 

We can say samples X_i are independent variables and are identically distributed if they are unbiased, which is a fair conckusion given that one sample's values of population will not effect another sample's result (there is replacement). 

a) Prove the expected value of sample mean is the population mean:

E(X) = E(1/n . sum(X_i))

= 1/n . E(sum(X_i))

Given the identitical distribution, we can say the E(X_i) = P(X = x).x_j = 1/N . sum(x_j).

= 1/n . sum(sum 1/N . (x_i))

= 1/N . sum(1/n_j) . sum(x_i)

= 1/N . sum(x_j)

= population mean as defined.

b) Prove the expected value of sample variance is the population variance:

Given that X_i are independent and identically distributed (iid), we can use the following premises in our proof:

1. We will calculate the same result for any of E( (X_i-X_bar^2)^2 ).
2. E(X_i.X_j) = E(X_i)E(X_j) = x_bar^2
3. E(X_i)^2 = sigma^2 + x_bar^2

Let us then use the normal calculations:

E ( (X_i - X_bar)^2 ) = E( X_i^2 - 2X_bar.X_i + X_bar^2).

= sigma^2 + x_bar^2 -2/n . [E(X_i^2) + sum(E(X_i.X_j)] + E(X_bar^2)

= sigma^2 + x_bar^2 -2/n . [sigma^2 + n.x_bar^2] + E(X_bar^2)

= (1-2/n).sigma^2 - x_bar^2 + E(1/(n^2).sum(X_i.X_j + X_i^2))

= (1-2/n).sigma^2 - x_bar^2 + 1/(n^2).sum(E(X_i.X_j)) + sum(E(X_i^2))

= (1-2/n).sigma^2 - x_bar^2 + (1-1/n)x_bar^2 + 1/n(sigma^2 + x_bar^2)

= 1-1/n . sigma^2

Now to the original proposition, 

E(s^2) = 1/(n-1) . sum(E( (X_i-X_bar^2)^2 )) 

= 1/(n-1) . sum((1-1/n).sigma^2)
       
= sigma^2 as desired.

*Question 3*

a) Systemic Sampling.

b) Simple Random Sampling.

c) Stratified Sampling.

*Question 4*

Group 1:

Ab3 (positive skew when highest frequency of events in lower ranges)

Group 2:

Bc2 (negative skew when highest frequency of events in higher ranges)

Group 3:

Ca1 (approximately normal with fat tails, median of data centered at 0 with outliers on both sides)
"""

# Question 5

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

M = []
F = []
A = []

with open('stat431heightgender.txt') as f:
    contents = f.readlines()

    for row in contents:
      fields = row.split("\t")
      gender, height = fields[0], fields[1]

      if gender == 'M':
        M.append(int(height))
      elif gender == 'F':
        F.append(int(height))
      
print(M)
print(F)

A = M + F

M = np.array(M)
F = np.array(F)
A = np.array(A)

print('The mean for males is ' + str(np.mean(M)))
print('The mean for females is ' + str(np.mean(F)))
print('The mean for the sample is ' + str(np.mean(A)))

print('The SD for males is ' + str(np.std(M)))
print('The SD for females is ' + str(np.std(F)))
print('The SD for the sample is ' + str(np.std(A)))

plt.boxplot(M)
print('There appear to be 2 outliers for males')

plt.boxplot(F)
print('There appears to be 1 outlier for females')

plt.boxplot(A)
print('There appear to be 2 outliers for the whole sample; one is male and one is female')

plt.hist(M)
print('All histograms are unimodal from the data and are roughly bell shaped. The male modal height is higher than the female height.')

plt.hist(F)

plt.hist(A)

import statsmodels.api as sm

print("All the QQ plots are approximately normal as demonstrated by the figures previously (histograms in particular). \nWe see that The larger outliers in the female/male QQ plot are reflected in the lack of linearity in the edge values particularly the left skew given the bottom is more divergent.")
fig = sm.qqplot(M)
plt.show()

fig = sm.qqplot(F)
plt.show()

fig = sm.qqplot(A)
plt.show()